# Vectorization
**Vectorization** is used to speed up the Python code without using loop. Using such a function can help in minimizing the running time of code efficiently. Various operations are being performed over vector such as dot product of vectors which is also known as scalar product as it produces single output, outer products which results in square matrix of dimension equal to length X length of the vectors, Element wise multiplication which products the element of same indexes and dimension of the matrix remain unchanged.

**Definition:** The process of transforming the input data (e.g., image, text) into a vector representation is called vectorization, which is an essential first step toward operating the artificial intelligence and machine learning algorithms

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)


In [ ]:
%time c = np.dot(a, b)

CPU times: user 3.72 ms, sys: 0 ns, total: 3.72 ms
Wall time: 1.91 ms


In [ ]:
def loop():
    c = 0
    for i in range(1000000):
        c += a[i] * b[i]

In [ ]:
%time loop()

CPU times: user 384 ms, sys: 0 ns, total: 384 ms
Wall time: 384 ms


# A note on python/numpy vectors

In [ ]:
a = np.random.randn(5)
a

array([-1.50768332, -0.34762576,  0.82402015, -0.15021025,  0.18177096])

In [ ]:
a.shape

(5,)

In [ ]:
a.T

array([-1.50768332, -0.34762576,  0.82402015, -0.15021025,  0.18177096])

In [ ]:
np.dot(a, a.T)

3.1285656758666973

In [ ]:
a = np.random.randn(5, 1)
a

array([[-1.45409815],
       [ 0.05631095],
       [ 0.37161622],
       [ 1.92252813],
       [-0.67568557]])

In [ ]:
a.shape

(5, 1)

In [ ]:
a.T

array([[-1.45409815,  0.05631095,  0.37161622,  1.92252813, -0.67568557]])

In [ ]:
np.dot(a, a.T)

array([[  2.11440143e+00,  -8.18816499e-02,  -5.40366459e-01,
         -2.79554460e+00,   9.82513134e-01],
       [ -8.18816499e-02,   3.17092321e-03,   2.09260628e-02,
          1.08259388e-01,  -3.80484969e-02],
       [ -5.40366459e-01,   2.09260628e-02,   1.38098615e-01,
          7.14442637e-01,  -2.51095716e-01],
       [ -2.79554460e+00,   1.08259388e-01,   7.14442637e-01,
          3.69611442e+00,  -1.29902451e+00],
       [  9.82513134e-01,  -3.80484969e-02,  -2.51095716e-01,
         -1.29902451e+00,   4.56550985e-01]])

Preprocessing of NLP data and feature extraction. [link text](https://www.kaggle.com/code/systemroomprint16/nlp-preprocessing-feature-extraction-methods-a-z)